/* Copyright (C)
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 * 
 */
/**
 * @file dmc_sparc.h
 * @brief The definition of system controller 
 * @author 
 * @version 78.77
 */

/* Autogenerated by SkyEye script */
#ifndef __DMC_SPARC_H__
#define __DMC_SPARC_H__

typedef struct dmc_sparc_reg
{
    uint32_t reset_reg;
    uint32_t write_fifo_reg;
    uint32_t status_reg;
    uint32_t read_status_reg;
    uint32_t read_fifo_reg;
    uint32_t clear_status_reg;
}dmc_sparc_reg_t;

typedef struct dmc_sparc_device
{
    conf_object_t* obj;
    dmc_sparc_reg_t* regs;
    conf_object_t* dmc_linker;
    dmc_linker_intf *dmc_linker_iface;
    FIFO* fifo;
    struct
    {
        general_signal_intf *signal_iface;
        conf_object_t *signal;
    } sparc_signal;
    int irq_number;
}dmc_sparc_device;


static char* regs_name[] =
{
    "reset_reg",
    "write_fifo_reg",
    "status_reg",
    "read_status_reg",
    "read_fifo_reg",
    "clear_status_reg",
    NULL
};
#endif
