/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file adk_rs422.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __ADK_RS422_H__
#define __ADK_RS422_H__

#define FIFO_SIZE	1024
#define UART_LEN 4

#define COM0_BASE 0xA0212000
#define COM1_BASE 0xA0223000
#define COM2_BASE 0xA0234000
#define COM3_BASE 0xA0245000
typedef struct adk_rs422_reg{
	uint32_t rx_fifo; 	//½ÓÊÕ»º´æÇø
	uint32_t tx_fifo; 	//ÆæÅ¼Ð£Ñé¼Ä´æÆ÷
	uint32_t ucr;  	//´®ÐÐ¿ØÖÆ¼Ä´æÆ÷ 
	uint32_t mcr;  	//µ÷ÖÆ½âµ÷Æ÷¿ØÖÆ¼Ä´æÆ÷ 0x20 ÔÊÐí½ÓÊÕ 
	uint32_t brsr;  	//²¨ÌØÂÊ¼Ä´æÆ÷ 
	uint32_t icr;  	//ÖÇÄÜ¿ØÖÆ¼Ä´æÆ÷
	uint32_t cmd;  	//ÃüÁî¼Ä´æÆ÷ 1-·¢ËÍ 0-½ÓÊÕ 
	uint32_t stu;  	//×´Ì¬¼Ä´æÆ÷
	uint32_t wrong_stu;  	//´íÎó×´Ì¬¼Ä´æÆ÷

    uint32_t tx_frame_head2;
    uint32_t tx_frame_head1;
    uint32_t rx_frame_head2;
    uint32_t rx_frame_head1;
}adk_rs422_reg_t;


typedef struct adk_rs422_device{
	conf_object_t* obj;
	adk_rs422_reg_t* regs;
	struct fifo{
		char send_buf[FIFO_SIZE];
		char recv_buf[FIFO_SIZE];
	}fifo;

	Rs422_bus_intf *bus_iface;
	conf_object_t *bus_obj;

    int Rs422_ID;

}adk_rs422_device;

#define RX_FIFO_REG (0x0 * UART_LEN)
#define TX_FIFO_REG (0x100 * UART_LEN)

#define UCR_REG (0x201 * UART_LEN)
#define MCR_REG (0x202 * UART_LEN)
#define BRSR_REG (0x203 * UART_LEN)
#define ICR_REG (0x204 * UART_LEN)
#define CMD_REG (0x300 * UART_LEN)
#define STU_REG (0x301 * UART_LEN)
#define WRONG_STU_REG (0x302 * UART_LEN)

#define TX_FRAME_HEAD_2 (0x205 * UART_LEN)
#define TX_FRAME_HEAD_1 (0x206 * UART_LEN)

#define RX_FRAME_HEAD_2 (0x207 * UART_LEN)
#define RX_FRAME_HEAD_1 (0x208 * UART_LEN)

static char* regs_name[] = {
	"rx_fifo",
	"tx_fifo",
	"ucr",
	"mcr",
	"brsr",
	"icr",
	"cmd",
	"stu",
	"wrong_stu",
	"tx_frame_head2",
	"tx_frame_head1",
	"rx_frame_head2",
	"rx_frame_head1",
	NULL
};
#define OK      0
#define Error  -1

#define SEND_CMD 0x81
#define RECV_CMD 0x82
#endif
