eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  level:
    com:
      iot:
        business:
          dao: trace
    root: info
  pattern:
    console: "'%p%m%n'"
server:
  port: 9005
  servlet:
    context-path: /web
spring:
  application:
    name: web
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1/iotdb?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
          username: iotdb
          password: www.5iot.com


    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 60000
      maximum-pool-size: 50
      minimum-idle: 10
  devtools:
    restart:
      enabled: true
  redis:
    host: localhost
    jedis:
      pool:
        max-active: 10
        max-idle: 20
        max-wait: -1
        min-idle: 10
    password: Rdis20220107
    port: 6379
    timeout: 10000
  rabbitmq:
    ####连接地址
    host: 127.0.0.1
    ####端口号
    port: 5672
    ####账号
    username: YunZeIotRabbitMq
    ####密码
    password: 20220107@yzIot
    ## 心跳  请求的心跳超时，以秒为单位； 零表示没有
    requested-heartbeat: 40
    ### 地址
    virtual-host: /VirtualHosts
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 1
          ####重试间隔时间
          initial-interval: 3000
        acknowledge-mode: auto

# MyBatis配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml