server:
  port: 1991
  servlet:
    session:
      timeout: 1h
  compression:
    enabled: true
    min-response-size: 1024
file-storage:
  local:
    root-path: ./files
custom-cache:
  entries:
    projectCache: 1d
    fileCache: 1h
    userCache: 1d
    deptCache: 1d
    projectPermissionCache: 1d
    commonCache: 30d