/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the * GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*

*/
/**
* @file timer_6713.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __vic_s3c6410_H__
#define __vic_s3c6410_H__

#define  VICIRQSTATUS			(0x000)  /*  IRQ  Status  Register  */
#define  VICFIQSTATUS			(0x004)  /*  FIQ  Status  Register  */
#define  VICRAWINTR			(0x008)  /*  Raw  Interrupt  Status  Register  */
#define  VICINTSELECT			(0x00C)  /*  Interrupt  Select  Register  */
#define  VICINTENABLE			(0x010)  /*  Interrupt  Enable  Register  */
#define  VICINTENCLEAR			(0x014)  /*  Interrupt  Enable  Clear  Register */
#define  VICSOFTINT			(0x018)  /*  Software  Interrupt  Register  */
#define  VICSOFTINTCLEAR		(0x01C)  /*  Software  Interrupt  Clear  Register */
#define  VICPROTECTION			(0x020)  /*  Protection  Enable  Register */
#define  VICSWPRIORITYMASK		(0x024)  /*  Software  Priority  Mask  Register  */
#define  VICPRIORITYDAISY		(0x028)  /*  Vector  Priority  Register  for  Daisy  Chain  */
#define  VICVECTADDR0			(0x100)  /*  Vector  Address  0  Register  */
#define  VICVECTADDR1			(0x104)  /*  Vector  Address  1  Register  */
#define  VICVECTADDR2			(0x108)  /*  Vector  Address  2  Register  */
#define  VICVECTADDR3			(0x10C)  /*  Vector  Address  3  Register  */
#define  VICVECTADDR4			(0x110)  /*  Vector  Address  4  Register  */
#define  VICVECTADDR5			(0x114)  /*  Vector  Address  5  Register  */
#define  VICVECTADDR6			(0x118)  /*  Vector  Address  6  Register  */
#define  VICVECTADDR7			(0x11C)  /*  Vector  Address  7  Register  */
#define  VICVECTADDR8			(0x120)  /*  Vector  Address  8  Register  */
#define  VICVECTADDR9			(0x124)  /*  Vector  Address  9  Register  */
#define  VICVECTADDR10			(0x128)  /*  Vector  Address  10  Register  */
#define  VICVECTADDR11			(0x12C)  /*  Vector  Address  11  Register  */
#define  VICVECTADDR12			(0x130)  /*  Vector  Address  12  Register  */
#define  VICVECTADDR13			(0x134)  /*  Vector  Address  13  Register  */
#define  VICVECTADDR14   		(0x138)  /*  Vector  Address  14  Register  */
#define  VICVECTADDR15   		(0x13C)  /*  Vector  Address  15  Register  */
#define  VICVECTADDR16   		(0x140)  /*  Vector  Address  16  Register  */
#define  VICVECTADDR17   		(0x144)  /*  Vector  Address  17  Register  */
#define  VICVECTADDR18   		(0x148)  /*  Vector  Address  18  Register  */
#define  VICVECTADDR19   		(0x14C)  /*  Vector  Address  19  Register  */
#define  VICVECTADDR20   		(0x150)  /*  Vector  Address  20  Register  */
#define  VICVECTADDR21   		(0x154)  /*  Vector  Address  21  Register  */
#define  VICVECTADDR22   		(0x158)  /*  Vector  Address  22  Register  */
#define  VICVECTADDR23   		(0x15C)  /*  Vector  Address  23  Register  */
#define  VICVECTADDR24   		(0x160)  /*  Vector  Address  24  Register  */
#define  VICVECTADDR25   		(0x164)  /*  Vector  Address  25  Register  */
#define  VICVECTADDR26   		(0x168)  /*  Vector  Address  26  Register  */
#define  VICVECTADDR27   		(0x16C)  /*  Vector  Address  27  Register  */
#define  VICVECTADDR28   		(0x170)  /*  Vector  Address  28  Register  */
#define  VICVECTADDR29   		(0x174)  /*  Vector  Address  29  Register  */
#define  VICVECTADDR30   		(0x178)  /*  Vector  Address  30  Register  */
#define  VICVECTADDR31   		(0x17C)  /*  Vector  Address  31  Register  */
#define  VICVECPRIORITY0 		(0x200)  /*  Vector  Priority  0  Register  */
#define  VICVECTPRIORITY1  	(0x204)  /*  Vector  Priority  1  Register  */
#define  VICVECTPRIORITY2  	(0x208)  /*  Vector  Priority  2  Register  */
#define  VICVECTPRIORITY3  	(0x20C)  /*  Vector  Priority  3  Register  */
#define  VICVECTPRIORITY4  	(0x210)  /*  Vector  Priority  4  Register  */
#define  VICVECTPRIORITY5  	(0x214)  /*  Vector  Priority  5  Register  */
#define  VICVECTPRIORITY6  	(0x218)  /*  Vector  Priority  6  Register  */
#define  VICVECTPRIORITY7  	(0x21C)  /*  Vector  Priority  7  Register  */
#define  VICVECTPRIORITY8  	(0x220)  /*  Vector  Priority  8  Register  */
#define  VICVECTPRIORITY9  	(0x224)  /*  Vector  Priority  9  Register  */
#define  VICVECTPRIORITY10  	(0x228)  /*  Vector  Priority  10  Register  */
#define  VICVECTPRIORITY11  	(0x22C)  /*  Vector  Priority  11  Register  */
#define  VICVECTPRIORITY12  	(0x230)  /*  Vector  Priority  12  Register  */
#define  VICVECTPRIORITY13  	(0x234)  /*  Vector  Priority  13  Register  */
#define  VICVECTPRIORITY14  	(0x238)  /*  Vector  Priority  14  Register  */
#define  VICVECTPRIORITY15  	(0x23C)  /*  Vector  Priority  15  Register  */
#define  VICVECTPRIORITY16  	(0x240)  /*  Vector  Priority  16  Register  */
#define  VICVECTPRIORITY17  	(0x244)  /*  Vector  Priority  17  Register  */
#define  VICVECTPRIORITY18  	(0x248)  /*  Vector  Priority  18  Register  */
#define  VICVECTPRIORITY19  	(0x24C)  /*  Vector  Priority  19  Register  */
#define  VICVECTPRIORITY20  	(0x250)  /*  Vector  Priority  20  Register  */
#define  VICVECTPRIORITY21  	(0x254)  /*  Vector  Priority  21  Register  */
#define  VICVECTPRIORITY22  	(0x258)  /*  Vector  Priority  22  Register  */
#define  VICVECTPRIORITY23  	(0x25C)  /*  Vector  Priority  23  Register  */
#define  VICVECTPRIORITY24  	(0x260)  /*  Vector  Priority  24  Register  */
#define  VICVECTPRIORITY25  	(0x264)  /*  Vector  Priority  25  Register  */
#define  VICVECTPRIORITY26  	(0x268)  /*  Vector  Priority  26  Register  */
#define  VICVECTPRIORITY27  	(0x26C)  /*  Vector  Priority  27  Register  */
#define  VICVECTPRIORITY28  	(0x270)  /*  Vector  Priority  28  Register  */
#define  VICVECTPRIORITY29  	(0x274)  /*  Vector  Priority  29  Register  */
#define  VICVECTPRIORITY30  	(0x278)  /*  Vector  Priority  30  Register  */
#define  VICVECTPRIORITY31  	(0x27C)  /*  Vector  Priority  31  Register  */
#define  VICADDRESS 		(0xF00)  /*  Vector  Address  Register  */


typedef struct s3c6410x_timer{
	conf_object_t *obj;
	struct registers{
		uint32_t  vic_irqstatus;    /*  IRQ  Status  Register  */
		uint32_t  vic_fiqstatus;    /*  FIQ  Status  Register  */
		uint32_t  vic_rawintr;      /*  Raw  Interrupt  Status  Register  */
		uint32_t  vic_intselect;    /*  Interrupt  Select  Register  */
		uint32_t  vic_intenable;    /*  Interrupt  Enable  Register  */
		uint32_t  vic_intenclear;    /*  Interrupt  Enable  Clear  Register */
		uint32_t  vic_softint;    	/*  Software  Interrupt  Register  */
		uint32_t  vic_softintclear;    /*  Software  Interrupt  Clear  Register */
		uint32_t  vic_protection;    /*  Protection  Enable  Register */
		uint32_t  vic_vectaddr[32];
		uint32_t  vic_address;
		uint32_t  vic_swprioritymask;    /*  Software  Priority  Mask  Register  */
		uint32_t  vic_prioritydaisy;    /*  Vector  Priority  Register  for  Daisy  Chain  */
		uint32_t  vic_vecpriority[32];
	}regs;
	core_signal_intf *signal_iface;
	conf_object_t *signal;
}vic_s3c6410_device;

static char* regs_name[] = {
	"irqstatus",
	"fiqstatus",
	"rawintr",      
	"intselect",   
	"intenable",    
	"intenclear",   
	"softint",      
	"softintclear", 
	"protection",    
	"vectaddr[0]",
	"vectaddr[1]",
	"vectaddr[2]",
	"vectaddr[3]",
	"vectaddr[4]",
	"vectaddr[5]",
	"vectaddr[6]",
	"vectaddr[7]",
	"vectaddr[8]",
	"vectaddr[9]",
	"vectaddr[10]",
	"vectaddr[11]",
	"vectaddr[12]",
	"vectaddr[13]",
	"vectaddr[14]",
	"vectaddr[15]",
	"vectaddr[16]",
	"vectaddr[17]",
	"vectaddr[18]",
	"vectaddr[19]",
	"vectaddr[20]",
	"vectaddr[21]",
	"vectaddr[22]",
	"vectaddr[23]",
	"vectaddr[24]",
	"vectaddr[25]",
	"vectaddr[26]",
	"vectaddr[27]",
	"vectaddr[28]",
	"vectaddr[29]",
	"vectaddr[30]",
	"vectaddr[31]",
	"address",
	"swprioritymask",    
	"prioritydaisy",    
	"vecpriority[0]",
	"vecpriority[1]",
	"vecpriority[2]", 
	"vecpriority[3]",
	"vecpriority[4]",
	"vecpriority[5]",
	"vecpriority[6]",
	"vecpriority[7]",
	"vecpriority[8]",
	"vecpriority[9]",
	"vecpriority[10]",
	"vecpriority[11]",
	"vecpriority[12]",
	"vecpriority[13]",
	"vecpriority[14]",
	"vecpriority[15]",
	"vecpriority[16]",
	"vecpriority[17]",
	"vecpriority[18]",
	"vecpriority[19]",
	"vecpriority[20]",
	"vecpriority[21]",
	"vecpriority[22]",
	"vecpriority[23]",
	"vecpriority[24]",
	"vecpriority[25]",
	"vecpriority[26]",
	"vecpriority[27]",
	"vecpriority[28]",
	"vecpriority[29]",
	"vecpriority[30]",
	"vecpriority[31]",
	NULL,

};

#endif

