name: Mirror GitHub Auto Queried Repos to Gitee
on:
  push:
    branches:
      - 'develop'
      - 'master'
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/Sora233
          dst: gitee/sora233
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "DDBOT"
          force_update: true