eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com:
      iot:
        business:
          dao: trace
    root: info
  pattern:
    console: "'%p%m%n'"
server:
  port: 9002
  servlet:
    context-path: /wechat
spring:
  application:
    name: wechat
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1/iotdb?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
          username: iotdb
          password: www.5iot.com

    hikari:
      connection-timeout: 60000
      max-lifetime: 60000
  devtools:
    restart:
      enabled: true
  redis:
    host: localhost
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        min-idle: 10
    password: Rdis20220107
    port: 6379
    timeout: 10000
  resources:
    static-locations: classpath:/static/
