header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - 'parser/AST.go'
    - 'parser/thrift.peg.go'
    - 'plugin/protocol.go'

  comment: on-failure
