name: Release

on:
  push:
    tags: 
      - 'v*'

jobs:
  example-frp-go-v2:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: ls
        run:  ls -alh

      - name: tidy
        run: go mod tidy
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            freebsd_386_vdns.tar.gz
            freebsd_amd64_vdns.tar.gz
            freebsd_arm64_vdns.tar.gz
            linux_386_vdns.tar.gz
            linux_amd64_vdns.tar.gz
            linux_arm64_vdns.tar.gz
            linux_armv5_vdns.tar.gz
            linux_armv6_vdns.tar.gz
            linux_armv7_vdns.tar.gz
            linux_mips64le_vdns.tar.gz
            linux_mips64_vdns.tar.gz
            linux_mipsle_vdns.tar.gz
            linux_mips_vdns.tar.gz
            darwin_amd64_vdns.tar.gz
            darwin_arm64_vdns.tar.gz
            windows_386_vdns.tar.gz
            windows_amd64_vdns.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
