/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file timer_6713.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __timer_leon2_H__
#define __timer_leon2_H__

typedef struct timer_leon2_reg{
	uint32_t timercnt1;    /* 0x40 */
	uint32_t timerload1;
	uint32_t timerctrl1;
	uint32_t wdog;
	uint32_t timercnt2;
	uint32_t timerload2;
	uint32_t timerctrl2;
	uint32_t dummy8;
	uint32_t scalercnt;
	uint32_t scalerload;
}timer_leon2_reg_t;

typedef struct timer_leon2_device{
	conf_object_t* obj;
	timer_leon2_reg_t* regs;
	int timer_scheduler_id;
	conf_object_t* signal;
	general_signal_intf* signal_iface;
	int interrupt_number;
	uint32_t address;
	uint32_t length;
}timer_leon2_device;

static char* regs_name[] = {
	"timercnt1",
	"timerload1",
	"timerctrl1",
	"wdog",
	"timercnt2",
	"timerload2",
	"timerctrl2",
	"dummy8",
	"scalercnt",
	"scalerload",
	NULL
};
#endif

/* control registers */

#define	TCNT1	0x00
#define	TLOAD1	0x04
#define	TCTRL1	0x08
#define	WDOG	0x0c
#define	TCNT2	0x10
#define	TLOAD2	0x14
#define TCTRL2	0x18
#define DMMY	0x1c
#define SCNT	0x20
#define SLOAD	0x24
