/* Copyright (C)
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.  *
*/
/**
* @file nvic_2410.h
* @brief The definition of system controller
* @author
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __nvic_stm32f0xx_H__
#define __nvic_stm32f0xx_H__

#include <skyeye_lock.h>

#define ISER   	(0x00)
#define ICER         (0x80)
#define ISPR         (0x100)
#define ICPR         (0x180)
#define IPR0         (0x300)
#define IPR_NUM         (8)

typedef struct stm32f0xxx_nvic {
	conf_object_t *obj;
	struct registers {
		uint32_t iser;
		uint32_t icer;
		uint32_t ispr;
		uint32_t icpr;
		uint32_t ipr[IPR_NUM];
	}regs;
	int scheduler_id;
	
	general_signal_intf *signal_iface;
	conf_object_t *signal;
	int interrupt_number;
	RWLOCK_T rttlock;
	RWLOCK_T wdtlock;
	RWLOCK_T pitlock;

	uint32_t sig_no;
}nvic_stm32f0xx_device;

static char* regs_name[] = {
	"cpuid",
	"icsr",
	"aircr",
	"scr",
	"ccr",
	"shpr2",
	"shpr3",
	 NULL
};
#endif
