/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file timer_6713.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __io_leon2_H__
#define __io_leon2_H__

typedef struct io_leon2_reg{
	uint32_t piodata;
	uint32_t piodir;
	uint32_t pioirq;
}io_leon2_reg_t;

typedef struct io_leon2_device{
	conf_object_t* obj;
	io_leon2_reg_t* regs;
	conf_object_t* signal;
	general_signal_intf* signal_iface;
	int int_number;
}io_leon2_device;

static char* regs_name[] = {
	"piodata",
	"piodir",
	"pioirq",
	NULL
};

#define PIO_DATA    0x0
#define PIO_DIR     0x4
#define PIO_IRQ     0x8

#endif
