/* Copyright (C)
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*
*/
/**
* @file timer_am3359.h
* @brief The definition of system controller
* @author Kewei Yu: keweihk@gmail.com
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __timer_am3359_H__
#define __timer_am3359_H__
#include <stdint.h>
#include <skyeye_lock.h>

#define INTERVAL 100
typedef struct am3359_timer{
	conf_object_t *obj;
	struct registers{
		uint32_t tidr;
		uint32_t tiocp_cfg;
		uint32_t irq_eoi;
		uint32_t irqstatus_raw;
		uint32_t irqstatus;
		uint32_t irqenable_set;
		uint32_t irqenable_clr;
		uint32_t irqwakeen;
		uint32_t tclr;
		uint32_t tcrr;
		uint32_t tldr;
		uint32_t ttgr;
		uint32_t twps;
		uint32_t tmar;
		uint32_t tcar1;
		uint32_t tsicr;
		uint32_t tcar2;
	}regs;

	int scheduler_id;
	uint32_t irqenable;
	general_signal_intf *signal_iface;
	conf_object_t *signal;
	int interrupt_number;
	RWLOCK_T lock;
}timer_am3359_device;

static char *regs_name[] = {
	"tidr",
	"tiocp_cfg",
	"irq_eoi",
	"irqstatus_raw",
	"irqstatus",
	"irqenable_set",
	"irqenable_clr",
	"irqwakeen",
	"tclr",
	"tcrr",
	"tldr",
	"ttgr",
	"twps",
	"tmar",
	"tcar1",
	"tsicr",
	"tcar2",
	NULL,
};

#define DMTIMER_TIDR		(0x0)
#define DMTIMER_TIOCP_CFG	(0x10)
#define DMTIMER_IRQ_EOI		(0x20)
#define DMTIMER_IRQSTATUS_RAW	(0x24)
#define DMTIMER_IRQSTATUS	(0x28)
#define DMTIMER_IRQENABLE_SET	(0x2C)
#define DMTIMER_IRQENABLE_CLR	(0x30)
#define DMTIMER_IRQWAKEEN	(0x34)
#define DMTIMER_TCLR		(0x38)
#define DMTIMER_TCRR		(0x3C)
#define DMTIMER_TLDR		(0x40)
#define DMTIMER_TTGR		(0x44)
#define DMTIMER_TWPS		(0x48)
#define DMTIMER_TMAR		(0x4C)
#define DMTIMER_TCAR1		(0x50)
#define DMTIMER_TSICR		(0x54)
#define DMTIMER_TCAR2		(0x58)

#endif
