apiVersion: apps/v1
kind: Deployment
metadata:
  name: megaide
spec:
  selector:
    matchLabels:
      app: megaide
  replicas: 1
  template:
    metadata:
      labels:
        app: megaide
    spec:
      hostAliases:
        - ip:
          hostnames:
            - "argo.lab.cc"
      volumes:
        - name: kube
          hostPath:
            path: /root/.kube/
        - name: docker
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: megaide
          image:
          imagePullPolicy: Always
          env:
            - name: APP_HOST
              value: ""
            - name: APP_PORT
              value: ""
            - name: ENV
              value: ""
            - name: KUBERNETES_NAMESPACE
              value: ""
            - name: KUBE_CONFIG_FILE
              value: ""
            - name: ARGO_URL
              value: ""
            - name: DB_URL
              value: ""
          volumeMounts:
            - name: kube
              mountPath: /root/.kube/
            - name: docker
              mountPath: /var/run/docker.sock
          ports:
            - containerPort: 8001
          command:
            - sh
            - /opt/start-server.sh

---
apiVersion: v1
kind: Service
metadata:
  name: megaide
spec:
  selector:
    app: megaide
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: app-8001
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: megaide
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`megaide.lab.cc`)
      kind: Rule
      services:
        - name: megaide
          port: 8001