apiVersion: apps/v1
kind: Deployment
metadata:
  name: megaide-worker
spec:
  selector:
    matchLabels:
      app: megaide-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: megaide-worker
    spec:
      hostAliases:
        - ip:
          hostnames:
             - "argo.lab.cc"
      containers:
        - name: megaide-worker
          image:
          imagePullPolicy: Always
          env:
            - name: APP_HOST
              value: ""
            - name: APP_PORT
              value: ""
            - name: ENV
              value: ""
            - name: KUBERNETES_NAMESPACE
              value: ""
            - name: KUBE_CONFIG_FILE
              value: ""
            - name: ARGO_URL
              value: ""
            - name: DB_URL
              value: ""

          command:
            - sh
            - /opt/start-worker.sh