/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file timer_6713.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __GPIO_CONNECTOR_H__
#define __GPIO_CONNECTOR_H__

/*GPIO logic gate interface*/
typedef enum{
	EQ_GATE = 0,
	AND_GATE,
	OR_GATE,
	NOT_GATE,
	NAND_GATE,
	NOR_GATE,
	XOR_GATE,
	/*add gate type*/
	
	/***************/
	UNKNOWN_GATE
}gate_type_t;

typedef struct gpio{
	conf_object_t* obj;
	conf_object_t **gpio_group;
	uint32_t gpio_num;
	uint32_t update_value;
	gate_type_t gate_type;
	conf_object_t *gate_a;
	skyeye_gate_a_intf *gate_a_iface;
	uint32_t gate_a_value;
	conf_object_t *gate_b;
	skyeye_gate_b_intf *gate_b_iface;
	uint32_t gate_b_value;
	uint32_t output_value;
	uint32_t NOT_gate_value;
}gpio_connector_device;

#define INPUT_UPDATE  (dev->update_value)
#define INPUT_A (dev->gate_a_value)
#define INPUT_B (dev->gate_b_value)
#define INPUT_NOT (dev->gate_b_value)

#define OUTPUT  (dev->output_value)

#endif


