/* Copyright (C)
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.  *
*/
/**
* @file scb_2410.h
* @brief The definition of system controller
* @author
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __scb_stm32f0xx_H__
#define __scb_stm32f0xx_H__

#include <skyeye_lock.h>

#define CPUID   	(0x00)
#define ICSR         (0x04)
#define AIRCR         (0x0C)
#define SCR         (0x10)
#define CCR         (0x14)
#define SHPR2         (0x1C)
#define SHPR3         (0x20)

typedef struct stm32f0xxx_scb {
	conf_object_t *obj;
	struct registers {
		uint32_t cpuid;
		uint32_t icsr;
		uint32_t aircr;
		uint32_t scr;
		uint32_t ccr;
		uint32_t shpr2;
		uint32_t shpr3;
	}regs;
	int scheduler_id;
	
	general_signal_intf *signal_iface;
	conf_object_t *signal;
	int interrupt_number;
	RWLOCK_T rttlock;
	RWLOCK_T wdtlock;
	RWLOCK_T pitlock;

	uint32_t sig_no;
}scb_stm32f0xx_device;

static char* regs_name[] = {
	"cpuid",
	"icsr",
	"aircr",
	"scr",
	"ccr",
	"shpr2",
	"shpr3",
	 NULL
};
#endif
