apiVersion: v1
kind: Service
metadata:
  name: ide-{{id}}
spec:
  selector:
    app: ide-{{id}}
{% if node_ports | length%}
  type: NodePort
{% endif %}
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    name: ide-port
{% if node_ports | length%}
{% set ports = node_ports.split(',') %}
{% for port in ports%}
  {% set port_config = port.split(':') %}
  - protocol: TCP
    port: {{port_config[1]}}
    targetPort: {{port_config[1]}}
    nodePort: {{port_config[0]}}
    name: port-{{port_config[1]}}
{% endfor %}
{% endif %}