/* Copyright (C)
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.  *
*/
/**
* @file systimer_2410.h
* @brief The definition of system controller
* @author
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __systimer_at91rm9200_H__
#define __systimer_at91rm9200_H__

#include <skyeye_lock.h>

#define ST_CR          	(0x00)
#define ST_PIMR         (0x04)
#define ST_WDMR         (0x08)
#define ST_RTMR         (0x0c)
#define ST_SR           (0x10)
#define ST_IER          (0x14)
#define ST_IDR          (0x18)
#define ST_IMR          (0x1c)
#define ST_RTAR         (0x20)
#define ST_CRTR         (0x24)



typedef struct at91rm9200x_systimer {
	conf_object_t *obj;
	struct registers {
		uint32_t st_cr;
		uint32_t st_pimr;
		uint32_t st_wdmr;
		uint32_t st_rtmr;
		uint32_t st_sr;
		uint32_t st_ier;
		uint32_t st_idr;
		uint32_t st_imr;
		uint32_t st_rtar;
		uint32_t st_crtr;
	}regs;
	int scheduler_id;
	int wdt_thr_id;
	int rtt_thr_id;

	uint32_t st_piv_dc;
	uint32_t st_wdv_dc;

	general_signal_intf *signal_iface;
	conf_object_t *signal;
	int interrupt_number;
	RWLOCK_T rttlock;
	RWLOCK_T wdtlock;
	RWLOCK_T pitlock;

	uint32_t sig_no;
}systimer_at91rm9200_device;

static char* regs_name[] = {
	"st_cr",
	"st_pimr",
	"st_wdmr",
	"st_rtmr",
	"st_sr",
	"st_ier",
	"st_idr",
	"st_imr",
	"st_rtar",
	"st_crtr",
	 NULL
};
#endif
