name: Preview Deploy

on:
  workflow_run:
    workflows: ['Preview Build']
    types: [completed]

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Update status comment
        uses: actions-cool/maintain-one-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Hi 😀, The preview site is being deployed...please wait...
            <!-- Created by Varlet -->
          body-include: '<!-- Created by Varlet -->'

      - name: Download pr number
        uses: dawidd6/action-download-artifact@v2
        with:
          name: pr
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Output pr number
        id: pr
        run: echo "::set-output name=id::$(<pr.txt)"

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: site
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Upload surge service
        run: |
          npx surge --project ./ --domain https://preview-${{ steps.pr.outputs.id }}-varlet-ui.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Update status comment
        uses: actions-cool/maintain-one-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            [<img width="310" src="https://varlet.gitee.io/varlet-ui/preview_success.png">](https://preview-${{ steps.pr.outputs.id }}-varlet-ui.surge.sh)
            <!-- Created by Varlet -->
          body-include: '<!-- Created by Varlet -->'
          number: ${{ steps.pr.outputs.id }}

      - name: The job has failed
        if: ${{ failure() }}
        uses: actions-cool/maintain-one-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            <img width="310" src="https://varlet.gitee.io/varlet-ui/preview_error.png">
            <!-- Created by Varlet -->
          body-include: '<!-- Created by Varlet -->'
          number: ${{ steps.pr.outputs.id }}
