// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: hashx.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HKeys []string `protobuf:"bytes,2,rep,name=h_keys,json=hKeys,proto3" json:"h_keys,omitempty"`
}

func (x *HDelRequest) Reset() {
	*x = HDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDelRequest) ProtoMessage() {}

func (x *HDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDelRequest.ProtoReflect.Descriptor instead.
func (*HDelRequest) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{0}
}

func (x *HDelRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HDelRequest) GetHKeys() []string {
	if x != nil {
		return x.HKeys
	}
	return nil
}

type HDelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HDelResponse) Reset() {
	*x = HDelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDelResponse) ProtoMessage() {}

func (x *HDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDelResponse.ProtoReflect.Descriptor instead.
func (*HDelResponse) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{1}
}

type HExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HKey string   `protobuf:"bytes,2,opt,name=h_key,json=hKey,proto3" json:"h_key,omitempty"`
}

func (x *HExistsRequest) Reset() {
	*x = HExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HExistsRequest) ProtoMessage() {}

func (x *HExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HExistsRequest.ProtoReflect.Descriptor instead.
func (*HExistsRequest) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{2}
}

func (x *HExistsRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HExistsRequest) GetHKey() string {
	if x != nil {
		return x.HKey
	}
	return ""
}

type HExistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *HExistsResponse) Reset() {
	*x = HExistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HExistsResponse) ProtoMessage() {}

func (x *HExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HExistsResponse.ProtoReflect.Descriptor instead.
func (*HExistsResponse) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{3}
}

func (x *HExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type HGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HKeys []string `protobuf:"bytes,2,rep,name=h_keys,json=hKeys,proto3" json:"h_keys,omitempty"`
}

func (x *HGetRequest) Reset() {
	*x = HGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetRequest) ProtoMessage() {}

func (x *HGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetRequest.ProtoReflect.Descriptor instead.
func (*HGetRequest) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{4}
}

func (x *HGetRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HGetRequest) GetHKeys() []string {
	if x != nil {
		return x.HKeys
	}
	return nil
}

type HGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[string]string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HGetResponse) Reset() {
	*x = HGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetResponse) ProtoMessage() {}

func (x *HGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetResponse.ProtoReflect.Descriptor instead.
func (*HGetResponse) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{5}
}

func (x *HGetResponse) GetItems() map[string]string {
	if x != nil {
		return x.Items
	}
	return nil
}

type HGetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HGetAllRequest) Reset() {
	*x = HGetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HGetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetAllRequest) ProtoMessage() {}

func (x *HGetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetAllRequest.ProtoReflect.Descriptor instead.
func (*HGetAllRequest) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{6}
}

func (x *HGetAllRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type HGetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[string]string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HGetAllResponse) Reset() {
	*x = HGetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HGetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetAllResponse) ProtoMessage() {}

func (x *HGetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetAllResponse.ProtoReflect.Descriptor instead.
func (*HGetAllResponse) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{7}
}

func (x *HGetAllResponse) GetItems() map[string]string {
	if x != nil {
		return x.Items
	}
	return nil
}

type HIncrByRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HKeys   []string `protobuf:"bytes,2,rep,name=h_keys,json=hKeys,proto3" json:"h_keys,omitempty"`
	Renewal int32    `protobuf:"varint,3,opt,name=renewal,proto3" json:"renewal,omitempty"`
}

func (x *HIncrByRequest) Reset() {
	*x = HIncrByRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HIncrByRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HIncrByRequest) ProtoMessage() {}

func (x *HIncrByRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HIncrByRequest.ProtoReflect.Descriptor instead.
func (*HIncrByRequest) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{8}
}

func (x *HIncrByRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HIncrByRequest) GetHKeys() []string {
	if x != nil {
		return x.HKeys
	}
	return nil
}

func (x *HIncrByRequest) GetRenewal() int32 {
	if x != nil {
		return x.Renewal
	}
	return 0
}

type HIncrByResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count  int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *HIncrByResponse) Reset() {
	*x = HIncrByResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HIncrByResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HIncrByResponse) ProtoMessage() {}

func (x *HIncrByResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HIncrByResponse.ProtoReflect.Descriptor instead.
func (*HIncrByResponse) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{9}
}

func (x *HIncrByResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *HIncrByResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type HKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HKeysRequest) Reset() {
	*x = HKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HKeysRequest) ProtoMessage() {}

func (x *HKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HKeysRequest.ProtoReflect.Descriptor instead.
func (*HKeysRequest) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{10}
}

func (x *HKeysRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type HKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *HKeysResponse) Reset() {
	*x = HKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HKeysResponse) ProtoMessage() {}

func (x *HKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HKeysResponse.ProtoReflect.Descriptor instead.
func (*HKeysResponse) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{11}
}

func (x *HKeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type HLenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HLenRequest) Reset() {
	*x = HLenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HLenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLenRequest) ProtoMessage() {}

func (x *HLenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLenRequest.ProtoReflect.Descriptor instead.
func (*HLenRequest) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{12}
}

func (x *HLenRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type HLenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length int32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *HLenResponse) Reset() {
	*x = HLenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HLenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLenResponse) ProtoMessage() {}

func (x *HLenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLenResponse.ProtoReflect.Descriptor instead.
func (*HLenResponse) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{13}
}

func (x *HLenResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type HSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *BaseKey          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Items map[string]string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HSetRequest) Reset() {
	*x = HSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetRequest) ProtoMessage() {}

func (x *HSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetRequest.ProtoReflect.Descriptor instead.
func (*HSetRequest) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{14}
}

func (x *HSetRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HSetRequest) GetItems() map[string]string {
	if x != nil {
		return x.Items
	}
	return nil
}

type HSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HSetResponse) Reset() {
	*x = HSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetResponse) ProtoMessage() {}

func (x *HSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetResponse.ProtoReflect.Descriptor instead.
func (*HSetResponse) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{15}
}

type HSetXRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *BaseKey          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Items map[string]string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HSetXRequest) Reset() {
	*x = HSetXRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HSetXRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetXRequest) ProtoMessage() {}

func (x *HSetXRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetXRequest.ProtoReflect.Descriptor instead.
func (*HSetXRequest) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{16}
}

func (x *HSetXRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HSetXRequest) GetItems() map[string]string {
	if x != nil {
		return x.Items
	}
	return nil
}

type HSetXResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *HSetXResponse) Reset() {
	*x = HSetXResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashx_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HSetXResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetXResponse) ProtoMessage() {}

func (x *HSetXResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashx_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetXResponse.ProtoReflect.Descriptor instead.
func (*HSetXResponse) Descriptor() ([]byte, []int) {
	return file_hashx_proto_rawDescGZIP(), []int{17}
}

func (x *HSetXResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_hashx_proto protoreflect.FileDescriptor

var file_hashx_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0b, 0x48, 0x44, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x4b, 0x65, 0x79, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x48,
	0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x41, 0x0a, 0x0e, 0x48,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x13, 0x0a, 0x05, 0x68, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x4b, 0x65, 0x79, 0x22, 0x29,
	0x0a, 0x0f, 0x48, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x40, 0x0a, 0x0b, 0x48, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x4b, 0x65, 0x79, 0x73, 0x22, 0x78, 0x0a, 0x0c, 0x48,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x48, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2c, 0x0a, 0x0e, 0x48, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x7e, 0x0a, 0x0f, 0x48, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x48, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x5d, 0x0a, 0x0e, 0x48, 0x49, 0x6e, 0x63, 0x72, 0x42, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x68, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6e, 0x65,
	0x77, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x6e, 0x65, 0x77,
	0x61, 0x6c, 0x22, 0x3f, 0x0a, 0x0f, 0x48, 0x49, 0x6e, 0x63, 0x72, 0x42, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x0c, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x23, 0x0a, 0x0d, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x22, 0x29, 0x0a, 0x0b, 0x48, 0x4c, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x26, 0x0a, 0x0c, 0x48, 0x4c, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x92, 0x01, 0x0a, 0x0b, 0x48, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x48, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x0e, 0x0a, 0x0c,
	0x48, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x94, 0x01, 0x0a,
	0x0c, 0x48, 0x53, 0x65, 0x74, 0x58, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x48, 0x53, 0x65, 0x74, 0x58,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x25, 0x0a, 0x0d, 0x48, 0x53, 0x65, 0x74, 0x58, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hashx_proto_rawDescOnce sync.Once
	file_hashx_proto_rawDescData = file_hashx_proto_rawDesc
)

func file_hashx_proto_rawDescGZIP() []byte {
	file_hashx_proto_rawDescOnce.Do(func() {
		file_hashx_proto_rawDescData = protoimpl.X.CompressGZIP(file_hashx_proto_rawDescData)
	})
	return file_hashx_proto_rawDescData
}

var file_hashx_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_hashx_proto_goTypes = []interface{}{
	(*HDelRequest)(nil),     // 0: HDelRequest
	(*HDelResponse)(nil),    // 1: HDelResponse
	(*HExistsRequest)(nil),  // 2: HExistsRequest
	(*HExistsResponse)(nil), // 3: HExistsResponse
	(*HGetRequest)(nil),     // 4: HGetRequest
	(*HGetResponse)(nil),    // 5: HGetResponse
	(*HGetAllRequest)(nil),  // 6: HGetAllRequest
	(*HGetAllResponse)(nil), // 7: HGetAllResponse
	(*HIncrByRequest)(nil),  // 8: HIncrByRequest
	(*HIncrByResponse)(nil), // 9: HIncrByResponse
	(*HKeysRequest)(nil),    // 10: HKeysRequest
	(*HKeysResponse)(nil),   // 11: HKeysResponse
	(*HLenRequest)(nil),     // 12: HLenRequest
	(*HLenResponse)(nil),    // 13: HLenResponse
	(*HSetRequest)(nil),     // 14: HSetRequest
	(*HSetResponse)(nil),    // 15: HSetResponse
	(*HSetXRequest)(nil),    // 16: HSetXRequest
	(*HSetXResponse)(nil),   // 17: HSetXResponse
	nil,                     // 18: HGetResponse.ItemsEntry
	nil,                     // 19: HGetAllResponse.ItemsEntry
	nil,                     // 20: HSetRequest.ItemsEntry
	nil,                     // 21: HSetXRequest.ItemsEntry
	(*BaseKey)(nil),         // 22: BaseKey
}
var file_hashx_proto_depIdxs = []int32{
	22, // 0: HDelRequest.key:type_name -> BaseKey
	22, // 1: HExistsRequest.key:type_name -> BaseKey
	22, // 2: HGetRequest.key:type_name -> BaseKey
	18, // 3: HGetResponse.items:type_name -> HGetResponse.ItemsEntry
	22, // 4: HGetAllRequest.key:type_name -> BaseKey
	19, // 5: HGetAllResponse.items:type_name -> HGetAllResponse.ItemsEntry
	22, // 6: HIncrByRequest.key:type_name -> BaseKey
	22, // 7: HKeysRequest.key:type_name -> BaseKey
	22, // 8: HLenRequest.key:type_name -> BaseKey
	22, // 9: HSetRequest.key:type_name -> BaseKey
	20, // 10: HSetRequest.items:type_name -> HSetRequest.ItemsEntry
	22, // 11: HSetXRequest.key:type_name -> BaseKey
	21, // 12: HSetXRequest.items:type_name -> HSetXRequest.ItemsEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_hashx_proto_init() }
func file_hashx_proto_init() {
	if File_hashx_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hashx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HDelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HExistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HGetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HGetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HIncrByRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HIncrByResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HLenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HLenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HSetXRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashx_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HSetXResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hashx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hashx_proto_goTypes,
		DependencyIndexes: file_hashx_proto_depIdxs,
		MessageInfos:      file_hashx_proto_msgTypes,
	}.Build()
	File_hashx_proto = out.File
	file_hashx_proto_rawDesc = nil
	file_hashx_proto_goTypes = nil
	file_hashx_proto_depIdxs = nil
}
