// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: listx.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Index int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *LIndexRequest) Reset() {
	*x = LIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LIndexRequest) ProtoMessage() {}

func (x *LIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LIndexRequest.ProtoReflect.Descriptor instead.
func (*LIndexRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{0}
}

func (x *LIndexRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LIndexRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type LIndexResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *LIndexResponse) Reset() {
	*x = LIndexResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LIndexResponse) ProtoMessage() {}

func (x *LIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LIndexResponse.ProtoReflect.Descriptor instead.
func (*LIndexResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{1}
}

func (x *LIndexResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type LLenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LLenRequest) Reset() {
	*x = LLenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLenRequest) ProtoMessage() {}

func (x *LLenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLenRequest.ProtoReflect.Descriptor instead.
func (*LLenRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{2}
}

func (x *LLenRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type LLenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length int32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *LLenResponse) Reset() {
	*x = LLenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLenResponse) ProtoMessage() {}

func (x *LLenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLenResponse.ProtoReflect.Descriptor instead.
func (*LLenResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{3}
}

func (x *LLenResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type LPopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Count int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *LPopRequest) Reset() {
	*x = LPopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopRequest) ProtoMessage() {}

func (x *LPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopRequest.ProtoReflect.Descriptor instead.
func (*LPopRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{4}
}

func (x *LPopRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LPopRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LPopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []string `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *LPopResponse) Reset() {
	*x = LPopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopResponse) ProtoMessage() {}

func (x *LPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopResponse.ProtoReflect.Descriptor instead.
func (*LPopResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{5}
}

func (x *LPopResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

type LPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LPushRequest) Reset() {
	*x = LPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushRequest) ProtoMessage() {}

func (x *LPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushRequest.ProtoReflect.Descriptor instead.
func (*LPushRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{6}
}

func (x *LPushRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LPushRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type LPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LPushResponse) Reset() {
	*x = LPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushResponse) ProtoMessage() {}

func (x *LPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushResponse.ProtoReflect.Descriptor instead.
func (*LPushResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{7}
}

type LPushXRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LPushXRequest) Reset() {
	*x = LPushXRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPushXRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushXRequest) ProtoMessage() {}

func (x *LPushXRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushXRequest.ProtoReflect.Descriptor instead.
func (*LPushXRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{8}
}

func (x *LPushXRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LPushXRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type LPushXResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LPushXResponse) Reset() {
	*x = LPushXResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPushXResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushXResponse) ProtoMessage() {}

func (x *LPushXResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushXResponse.ProtoReflect.Descriptor instead.
func (*LPushXResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{9}
}

type LRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start int32    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int32    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *LRangeRequest) Reset() {
	*x = LRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeRequest) ProtoMessage() {}

func (x *LRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeRequest.ProtoReflect.Descriptor instead.
func (*LRangeRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{10}
}

func (x *LRangeRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LRangeRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LRangeRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type LRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LRangeResponse) Reset() {
	*x = LRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeResponse) ProtoMessage() {}

func (x *LRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeResponse.ProtoReflect.Descriptor instead.
func (*LRangeResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{11}
}

func (x *LRangeResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type LRemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// count > 0 头搜索，count < 0 尾搜索
	Count int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LRemRequest) Reset() {
	*x = LRemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRemRequest) ProtoMessage() {}

func (x *LRemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRemRequest.ProtoReflect.Descriptor instead.
func (*LRemRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{12}
}

func (x *LRemRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LRemRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LRemRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LRemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *LRemResponse) Reset() {
	*x = LRemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRemResponse) ProtoMessage() {}

func (x *LRemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRemResponse.ProtoReflect.Descriptor instead.
func (*LRemResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{13}
}

func (x *LRemResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Index int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Value string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LSetRequest) Reset() {
	*x = LSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSetRequest) ProtoMessage() {}

func (x *LSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSetRequest.ProtoReflect.Descriptor instead.
func (*LSetRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{14}
}

func (x *LSetRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LSetRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LSetResponse) Reset() {
	*x = LSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSetResponse) ProtoMessage() {}

func (x *LSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSetResponse.ProtoReflect.Descriptor instead.
func (*LSetResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{15}
}

type RPopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Count int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *RPopRequest) Reset() {
	*x = RPopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPopRequest) ProtoMessage() {}

func (x *RPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPopRequest.ProtoReflect.Descriptor instead.
func (*RPopRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{16}
}

func (x *RPopRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RPopRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RPopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []string `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *RPopResponse) Reset() {
	*x = RPopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPopResponse) ProtoMessage() {}

func (x *RPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPopResponse.ProtoReflect.Descriptor instead.
func (*RPopResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{17}
}

func (x *RPopResponse) GetResult() []string {
	if x != nil {
		return x.Result
	}
	return nil
}

type LTrimRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start int32    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int32    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *LTrimRequest) Reset() {
	*x = LTrimRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LTrimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LTrimRequest) ProtoMessage() {}

func (x *LTrimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LTrimRequest.ProtoReflect.Descriptor instead.
func (*LTrimRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{18}
}

func (x *LTrimRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LTrimRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LTrimRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type LTrimResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LTrimResponse) Reset() {
	*x = LTrimResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LTrimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LTrimResponse) ProtoMessage() {}

func (x *LTrimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LTrimResponse.ProtoReflect.Descriptor instead.
func (*LTrimResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{19}
}

type RPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *RPushRequest) Reset() {
	*x = RPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushRequest) ProtoMessage() {}

func (x *RPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushRequest.ProtoReflect.Descriptor instead.
func (*RPushRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{20}
}

func (x *RPushRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RPushRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RPushResponse) Reset() {
	*x = RPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushResponse) ProtoMessage() {}

func (x *RPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushResponse.ProtoReflect.Descriptor instead.
func (*RPushResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{21}
}

type RPushXRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    *BaseKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *RPushXRequest) Reset() {
	*x = RPushXRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPushXRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushXRequest) ProtoMessage() {}

func (x *RPushXRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushXRequest.ProtoReflect.Descriptor instead.
func (*RPushXRequest) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{22}
}

func (x *RPushXRequest) GetKey() *BaseKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RPushXRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RPushXResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RPushXResponse) Reset() {
	*x = RPushXResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listx_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPushXResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushXResponse) ProtoMessage() {}

func (x *RPushXResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listx_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushXResponse.ProtoReflect.Descriptor instead.
func (*RPushXResponse) Descriptor() ([]byte, []int) {
	return file_listx_proto_rawDescGZIP(), []int{23}
}

var File_listx_proto protoreflect.FileDescriptor

var file_listx_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x0d, 0x4c, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x28, 0x0a, 0x0e,
	0x4c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x29, 0x0a, 0x0b, 0x4c, 0x4c, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x26, 0x0a, 0x0c, 0x4c, 0x4c, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x3f, 0x0a, 0x0b, 0x4c, 0x50, 0x6f,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x0c, 0x4c, 0x50,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x22, 0x42, 0x0a, 0x0c, 0x4c, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x43, 0x0a, 0x0d, 0x4c, 0x50, 0x75,
	0x73, 0x68, 0x58, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x10,
	0x0a, 0x0e, 0x4c, 0x50, 0x75, 0x73, 0x68, 0x58, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x53, 0x0a, 0x0d, 0x4c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x4c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0x55, 0x0a, 0x0b, 0x4c, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x24, 0x0a, 0x0c, 0x4c, 0x52, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x55, 0x0a, 0x0b,
	0x4c, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b,
	0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x0b, 0x52, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x52, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x52, 0x0a, 0x0c,
	0x4c, 0x54, 0x72, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x6e, 0x64,
	0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x54, 0x72, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x42, 0x0a, 0x0c, 0x52, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x43, 0x0a, 0x0d, 0x52, 0x50, 0x75, 0x73, 0x68, 0x58,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x52,
	0x50, 0x75, 0x73, 0x68, 0x58, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a,
	0x09, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_listx_proto_rawDescOnce sync.Once
	file_listx_proto_rawDescData = file_listx_proto_rawDesc
)

func file_listx_proto_rawDescGZIP() []byte {
	file_listx_proto_rawDescOnce.Do(func() {
		file_listx_proto_rawDescData = protoimpl.X.CompressGZIP(file_listx_proto_rawDescData)
	})
	return file_listx_proto_rawDescData
}

var file_listx_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_listx_proto_goTypes = []interface{}{
	(*LIndexRequest)(nil),  // 0: LIndexRequest
	(*LIndexResponse)(nil), // 1: LIndexResponse
	(*LLenRequest)(nil),    // 2: LLenRequest
	(*LLenResponse)(nil),   // 3: LLenResponse
	(*LPopRequest)(nil),    // 4: LPopRequest
	(*LPopResponse)(nil),   // 5: LPopResponse
	(*LPushRequest)(nil),   // 6: LPushRequest
	(*LPushResponse)(nil),  // 7: LPushResponse
	(*LPushXRequest)(nil),  // 8: LPushXRequest
	(*LPushXResponse)(nil), // 9: LPushXResponse
	(*LRangeRequest)(nil),  // 10: LRangeRequest
	(*LRangeResponse)(nil), // 11: LRangeResponse
	(*LRemRequest)(nil),    // 12: LRemRequest
	(*LRemResponse)(nil),   // 13: LRemResponse
	(*LSetRequest)(nil),    // 14: LSetRequest
	(*LSetResponse)(nil),   // 15: LSetResponse
	(*RPopRequest)(nil),    // 16: RPopRequest
	(*RPopResponse)(nil),   // 17: RPopResponse
	(*LTrimRequest)(nil),   // 18: LTrimRequest
	(*LTrimResponse)(nil),  // 19: LTrimResponse
	(*RPushRequest)(nil),   // 20: RPushRequest
	(*RPushResponse)(nil),  // 21: RPushResponse
	(*RPushXRequest)(nil),  // 22: RPushXRequest
	(*RPushXResponse)(nil), // 23: RPushXResponse
	(*BaseKey)(nil),        // 24: BaseKey
}
var file_listx_proto_depIdxs = []int32{
	24, // 0: LIndexRequest.key:type_name -> BaseKey
	24, // 1: LLenRequest.key:type_name -> BaseKey
	24, // 2: LPopRequest.key:type_name -> BaseKey
	24, // 3: LPushRequest.key:type_name -> BaseKey
	24, // 4: LPushXRequest.key:type_name -> BaseKey
	24, // 5: LRangeRequest.key:type_name -> BaseKey
	24, // 6: LRemRequest.key:type_name -> BaseKey
	24, // 7: LSetRequest.key:type_name -> BaseKey
	24, // 8: RPopRequest.key:type_name -> BaseKey
	24, // 9: LTrimRequest.key:type_name -> BaseKey
	24, // 10: RPushRequest.key:type_name -> BaseKey
	24, // 11: RPushXRequest.key:type_name -> BaseKey
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_listx_proto_init() }
func file_listx_proto_init() {
	if File_listx_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_listx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LIndexResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPushXRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPushXResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LTrimRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LTrimResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPushXRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listx_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPushXResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_listx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listx_proto_goTypes,
		DependencyIndexes: file_listx_proto_depIdxs,
		MessageInfos:      file_listx_proto_msgTypes,
	}.Build()
	File_listx_proto = out.File
	file_listx_proto_rawDesc = nil
	file_listx_proto_goTypes = nil
	file_listx_proto_depIdxs = nil
}
