/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file adk_kio.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __ADK_KIO_H__
#define __ADK_KIO_H__



typedef struct adk_kio_reg{
    uint32_t ki_ctrl; 
    uint32_t ko_ctrl; //KO输出使能
    uint32_t ad_data;
    uint32_t da_ctrl;
    uint32_t data_ctrl; //数据使能
    uint32_t ko_ctrl1;
    uint32_t ko_ctrl2;
}adk_kio_reg_t;

typedef struct adk_kio_device{
	conf_object_t* obj;
	adk_kio_reg_t* regs;
    union {
        uint16_t da_all;
        struct{
            uint8_t da_lsb;
            uint8_t da_msb;
        };
    }da_data[4];
}adk_kio_device;

#define REG_KICTRL      0x4
#define REG_KOCTRL      0x18
#define ADDR_DA_DATA    0x40
#define REG_DACTRL      0x60
#define REG_DATA_CTRL   0x100
#define	REG_KOCTRL1     0x2A8
#define	REG_KOCTRL2     0x2AC

static char* regs_name[] = {
    "ki_ctrl",
    "ko_ctrl",
    "ad_data",
    "da_ctrl",
    "data_ctrl",
    "ko_ctrl1",
    "ko_ctrl2",
	NULL
};

static uint32_t regs_offset[] = {
	0x4,
	0x18,
	0x40,
	0x60,
	0x100,
	0x2A8,
	0x2AC,
};
#define OK      0
#define Error  -1
#endif
