spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flink-admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver_class_namel: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    poolPreparedStatements: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 150MB
      max-request-size: 150MB
  # freemarker数字去掉自动加逗号
  freemarker:
    tempalte-loader-path=classpath: /templates
    suffix: .ftl
    settings:
      number_format: 0

# 日志配置:
logging:
  level:
    ROOT: INFO
    cn.chongho.inf.flink.mapper: debug
    tk.mybatis: debug
sys:
  #  url: http://192.168.46.21:8081
  url: http://172.16.5.7:8081
  savepoint-path: /home/flink/savepoints
  checkpoint-path: /home/flink/checkpoints
  des:
    secretkey: CF97166B99485FA6E186D6182B814EEE
    offset: 88888888
  upload:
    jar-path: E:\\tmp\\
