// Code generated by gen-struct. DO NOT EDIT.
// make gen-service generated

package dao

import (
	"gitee.com/wheat-os/wheatCache/pkg/proto"
	protobuf "google.golang.org/protobuf/proto"
)

type Interface interface {
	LIndex(*proto.BaseKey, int32) (*proto.LIndexResponse, error)
	LLen(*proto.BaseKey) (*proto.LLenResponse, error)
	LPop(*proto.BaseKey, int32) (*proto.LPopResponse, error)
	LPush(*proto.BaseKey, []string) (*proto.LPushResponse, error)
	LPushX(*proto.BaseKey, []string) (*proto.LPushXResponse, error)
	LRange(*proto.BaseKey, int32, int32) (*proto.LRangeResponse, error)
	LRem(*proto.BaseKey, int32, string) (*proto.LRemResponse, error)
	LSet(*proto.BaseKey, int32, string) (*proto.LSetResponse, error)
	RPop(*proto.BaseKey, int32) (*proto.RPopResponse, error)
	LTrim(*proto.BaseKey, int32, int32) (*proto.LTrimResponse, error)
	RPush(*proto.BaseKey, []string) (*proto.RPushResponse, error)
	RPushX(*proto.BaseKey, []string) (*proto.RPushXResponse, error)
	HDel(*proto.BaseKey, []string) (*proto.HDelResponse, error)
	HExists(*proto.BaseKey, string) (*proto.HExistsResponse, error)
	HGet(*proto.BaseKey, []string) (*proto.HGetResponse, error)
	HGetAll(*proto.BaseKey) (*proto.HGetAllResponse, error)
	HIncrBy(*proto.BaseKey, []string, int32) (*proto.HIncrByResponse, error)
	HKeys(*proto.BaseKey) (*proto.HKeysResponse, error)
	HLen(*proto.BaseKey) (*proto.HLenResponse, error)
	HSet(*proto.BaseKey, map[string]string) (*proto.HSetResponse, error)
	HSetX(*proto.BaseKey, map[string]string) (*proto.HSetXResponse, error)
	CPush(*proto.BaseKey, []string) (interface{}, error)
	CPop(*proto.BaseKey, int32) (interface{}, error)
	CMake(*proto.BaseKey, int32) (*proto.CMakeResponse, error)
	CLen(*proto.BaseKey) (*proto.CLenResponse, error)
	CClean(*proto.BaseKey) (*proto.CCleanResponse, error)
	Set(*proto.BaseKey, string) (*proto.SetResponse, error)
	Get(*proto.BaseKey) (*proto.GetResponse, error)
	Add(*proto.BaseKey, int32) (*proto.AddResponse, error)
	Reduce(*proto.BaseKey, int32) (*proto.ReduceResponse, error)
	Setnx(*proto.BaseKey, string) (*proto.SetnxResponse, error)
	SetBit(*proto.BaseKey, bool, int32) (*proto.SetBitResponse, error)
	GetBit(*proto.BaseKey, int32) (*proto.GetBitResponse, error)
	GetRange(*proto.BaseKey, int32, int32) (*proto.GetRangeResponse, error)
	GetSet(*proto.BaseKey, string) (*proto.GetSetResponse, error)
	StrLen(*proto.BaseKey) (*proto.StrLenResponse, error)
	SAdd(*proto.BaseKey, []string) (*proto.SAddResponse, error)
	SCard(*proto.BaseKey) (*proto.SCardResponse, error)
	SDiff(*proto.BaseKey, []string) (interface{}, error)
	SDiffStore(*proto.BaseKey, []string, string) (interface{}, error)
	SInter(*proto.BaseKey, []string) (interface{}, error)
	SInterStore(*proto.BaseKey, []string, string) (interface{}, error)
	SIsMember(*proto.BaseKey, string) (*proto.SIsMemberResponse, error)
	SMove(*proto.BaseKey, string, []string) (interface{}, error)
	SPop(*proto.BaseKey, int32) (*proto.SPopResponse, error)
	SRem(*proto.BaseKey, int32) (*proto.SRemResponse, error)
	SUnion(*proto.BaseKey, []string) (interface{}, error)
	SUnionStore(*proto.BaseKey, []string, string) (interface{}, error)
	SScan(*proto.BaseKey, int32, string, int32) (*proto.SScanResponse, error)
	ExecMessage(message protobuf.Message) error
}
