# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_package import skyeye_rpc_pb2 as skyeye__rpc__pb2


class JSONTransmissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallSkyEye = channel.unary_unary(
                '/JSONTransmission/CallSkyEye',
                request_serializer=skyeye__rpc__pb2.JSONRequest.SerializeToString,
                response_deserializer=skyeye__rpc__pb2.JSONResponse.FromString,
                )
        self.SkyEyeLogReport = channel.unary_stream(
                '/JSONTransmission/SkyEyeLogReport',
                request_serializer=skyeye__rpc__pb2.JSONRequest.SerializeToString,
                response_deserializer=skyeye__rpc__pb2.JSONResponse.FromString,
                )


class JSONTransmissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallSkyEye(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SkyEyeLogReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JSONTransmissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallSkyEye': grpc.unary_unary_rpc_method_handler(
                    servicer.CallSkyEye,
                    request_deserializer=skyeye__rpc__pb2.JSONRequest.FromString,
                    response_serializer=skyeye__rpc__pb2.JSONResponse.SerializeToString,
            ),
            'SkyEyeLogReport': grpc.unary_stream_rpc_method_handler(
                    servicer.SkyEyeLogReport,
                    request_deserializer=skyeye__rpc__pb2.JSONRequest.FromString,
                    response_serializer=skyeye__rpc__pb2.JSONResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JSONTransmission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JSONTransmission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallSkyEye(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JSONTransmission/CallSkyEye',
            skyeye__rpc__pb2.JSONRequest.SerializeToString,
            skyeye__rpc__pb2.JSONResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SkyEyeLogReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/JSONTransmission/SkyEyeLogReport',
            skyeye__rpc__pb2.JSONRequest.SerializeToString,
            skyeye__rpc__pb2.JSONResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
