# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skyeye_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='skyeye_rpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10skyeye_rpc.proto\"\x1e\n\x0bJSONRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\" \n\x0cJSONResponse\x12\x10\n\x08response\x18\x01 \x01(\t2s\n\x10JSONTransmission\x12+\n\nCallSkyEye\x12\x0c.JSONRequest\x1a\r.JSONResponse\"\x00\x12\x32\n\x0fSkyEyeLogReport\x12\x0c.JSONRequest\x1a\r.JSONResponse\"\x00\x30\x01\x62\x06proto3'
)




_JSONREQUEST = _descriptor.Descriptor(
  name='JSONRequest',
  full_name='JSONRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='JSONRequest.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=50,
)


_JSONRESPONSE = _descriptor.Descriptor(
  name='JSONResponse',
  full_name='JSONResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='JSONResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['JSONRequest'] = _JSONREQUEST
DESCRIPTOR.message_types_by_name['JSONResponse'] = _JSONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JSONRequest = _reflection.GeneratedProtocolMessageType('JSONRequest', (_message.Message,), {
  'DESCRIPTOR' : _JSONREQUEST,
  '__module__' : 'skyeye_rpc_pb2'
  # @@protoc_insertion_point(class_scope:JSONRequest)
  })
_sym_db.RegisterMessage(JSONRequest)

JSONResponse = _reflection.GeneratedProtocolMessageType('JSONResponse', (_message.Message,), {
  'DESCRIPTOR' : _JSONRESPONSE,
  '__module__' : 'skyeye_rpc_pb2'
  # @@protoc_insertion_point(class_scope:JSONResponse)
  })
_sym_db.RegisterMessage(JSONResponse)



_JSONTRANSMISSION = _descriptor.ServiceDescriptor(
  name='JSONTransmission',
  full_name='JSONTransmission',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=86,
  serialized_end=201,
  methods=[
  _descriptor.MethodDescriptor(
    name='CallSkyEye',
    full_name='JSONTransmission.CallSkyEye',
    index=0,
    containing_service=None,
    input_type=_JSONREQUEST,
    output_type=_JSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SkyEyeLogReport',
    full_name='JSONTransmission.SkyEyeLogReport',
    index=1,
    containing_service=None,
    input_type=_JSONREQUEST,
    output_type=_JSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JSONTRANSMISSION)

DESCRIPTOR.services_by_name['JSONTransmission'] = _JSONTRANSMISSION

# @@protoc_insertion_point(module_scope)
