/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file Lvds_c6k.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __LVDS_C6K_H__
#define __LVDS_C6K_H__

#define FIFO_SIZE	1024
typedef struct Lvds_c6k_reg{
	uint32_t recv_length_reg;
	uint32_t status_reg;
	uint32_t cmd_reg;
	uint32_t type_reg;
	uint32_t send_length_reg;

}Lvds_c6k_reg_t;

typedef struct Lvds_c6k_device{
	conf_object_t* obj;
	Lvds_c6k_reg_t* regs;
	int dev_id;
	int send_cnt;
	int data_length;
	int check_sum;
	Lvds_bus_intf *bus_iface;
	conf_object_t *bus_obj;
	char *ptr;
	char *send_cache;
	char *recv_cache;
}Lvds_c6k_device;

static char* regs_name[] = {
	"recv_length_reg", 
	"status_reg",
	"cmd_reg",
	"type_reg"
	"send_length_reg", 
	NULL
};
#define OK      0
#define Error  -1
#endif
