// Code generated by gen-struct. DO NOT EDIT.
// make gen-struct generated

package structure

const (
	DEFAULT_KEY = iota

	STRING_X
	LIST_X
	HASH_X
	SET_X
	CHANNEL_X
)

const (
	DEFAULT_COMM = iota
	Set
	Get
	Add
	Reduce
	SetBit
	GetBit
	GetRange
	GetSet
	StrLen
	Setnx
	LIndex
	LLen
	LPop
	LPush
	LPushX
	LRange
	LRem
	LSet
	RPop
	LTrim
	RPush
	RPushX
	HDel
	HExists
	HGet
	HGetAll
	HIncrBy
	HKeys
	HLen
	HSet
	HSetX
	SAdd
	SCard
	SDiff
	SDiffStore
	SInter
	SInterStore
	SIsMember
	SMove
	SPop
	SRem
	SUnion
	SUnionStore
	SScan
	CPush
	CPop
	CMake
	CLen
	CClean
)

var CommKeyString = map[string]int{
	"Set":      STRING_X,
	"Get":      STRING_X,
	"Add":      STRING_X,
	"Reduce":   STRING_X,
	"SetBit":   STRING_X,
	"GetBit":   STRING_X,
	"GetRange": STRING_X,
	"GetSet":   STRING_X,
	"StrLen":   STRING_X,
	"Setnx":    STRING_X,

	"LIndex": LIST_X,
	"LLen":   LIST_X,
	"LPop":   LIST_X,
	"LPush":  LIST_X,
	"LPushX": LIST_X,
	"LRange": LIST_X,
	"LRem":   LIST_X,
	"LSet":   LIST_X,
	"RPop":   LIST_X,
	"LTrim":  LIST_X,
	"RPush":  LIST_X,
	"RPushX": LIST_X,

	"HDel":    HASH_X,
	"HExists": HASH_X,
	"HGet":    HASH_X,
	"HGetAll": HASH_X,
	"HIncrBy": HASH_X,
	"HKeys":   HASH_X,
	"HLen":    HASH_X,
	"HSet":    HASH_X,
	"HSetX":   HASH_X,

	"SAdd":        SET_X,
	"SCard":       SET_X,
	"SDiff":       SET_X,
	"SDiffStore":  SET_X,
	"SInter":      SET_X,
	"SInterStore": SET_X,
	"SIsMember":   SET_X,
	"SMove":       SET_X,
	"SPop":        SET_X,
	"SRem":        SET_X,
	"SUnion":      SET_X,
	"SUnionStore": SET_X,
	"SScan":       SET_X,

	"CPush":  CHANNEL_X,
	"CPop":   CHANNEL_X,
	"CMake":  CHANNEL_X,
	"CLen":   CHANNEL_X,
	"CClean": CHANNEL_X,
}

var CommKey = map[int]int{
	Set:      STRING_X,
	Get:      STRING_X,
	Add:      STRING_X,
	Reduce:   STRING_X,
	SetBit:   STRING_X,
	GetBit:   STRING_X,
	GetRange: STRING_X,
	GetSet:   STRING_X,
	StrLen:   STRING_X,
	Setnx:    STRING_X,

	LIndex: LIST_X,
	LLen:   LIST_X,
	LPop:   LIST_X,
	LPush:  LIST_X,
	LPushX: LIST_X,
	LRange: LIST_X,
	LRem:   LIST_X,
	LSet:   LIST_X,
	RPop:   LIST_X,
	LTrim:  LIST_X,
	RPush:  LIST_X,
	RPushX: LIST_X,

	HDel:    HASH_X,
	HExists: HASH_X,
	HGet:    HASH_X,
	HGetAll: HASH_X,
	HIncrBy: HASH_X,
	HKeys:   HASH_X,
	HLen:    HASH_X,
	HSet:    HASH_X,
	HSetX:   HASH_X,

	SAdd:        SET_X,
	SCard:       SET_X,
	SDiff:       SET_X,
	SDiffStore:  SET_X,
	SInter:      SET_X,
	SInterStore: SET_X,
	SIsMember:   SET_X,
	SMove:       SET_X,
	SPop:        SET_X,
	SRem:        SET_X,
	SUnion:      SET_X,
	SUnionStore: SET_X,
	SScan:       SET_X,

	CPush:  CHANNEL_X,
	CPop:   CHANNEL_X,
	CMake:  CHANNEL_X,
	CLen:   CHANNEL_X,
	CClean: CHANNEL_X,
}
