/* Copyright (C)
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file uart_c5510.h
* @brief The definition of system controller 
* @author 
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __uart_c5510_H__
#define __uart_c5510_H__
#include "c5510_fifo.h"

typedef struct uart_c5510_reg{
	uint16_t rbr;		/* Receiver Buffer register  (read only) */
	uint16_t thr;		/* Transmitter Holding register (write only) */
	uint16_t ier;		/* Interrupt Enable register */
	uint16_t iir;		/* Interrupt identification register (read only)*/
	uint16_t fcr;		/* FIFO Control register (write only)*/
	uint16_t lcr;		/* Line Control register */
	uint16_t mcr;		/* Modem Control register */
	uint16_t lsr;		/* Line Status register */
	uint16_t scr;		/* Scratch register */
	uint16_t dll;		/* Divisor LSB Latch */
	uint16_t dlh;		/* Divisor MSB Latch */
	uint16_t pwremu_mgmt;		/* Power and Emulation Management register */
}uart_c5510_reg_t;

static char* regs_name[] ={
	"RBR",
	"THR",	
	"IER",	
	"IIR",	
	"FCR",	
	"LCR",
	"MCR",
	"LSR",
	"SCR",
	"DLL",	
	"DLH",	
	"PWREMU_MGMT",
	NULL
};

typedef struct uart_c5510{
	conf_object_t* obj;
	uart_c5510_reg_t* regs;
	skyeye_uart_intf* term_iface;
	conf_object_t* term;
	uart_file_intf *uart_file_iface;
	conf_object_t *uart_file;
	general_signal_intf* signal_iface;
	conf_object_t* signal;
	int int_number;
	char **regs_name;
	FIFO *read_fifo;
	int dev_enable;
}uart_c5510_device;

static uint32_t regs_offset[] = {
	0x0000,
	0x0000,
	0x0002,
	0x0004,
	0x0004,
	0x0006,
	0x0008,
	0x000A,
	0x000E,
	0x0010,
	0x0012,
	0x0018,
};
#define RBR		(0x0)  
#define THR		(0x0)  
#define IER		(0x2)  
#define IIR		(0x4)  
#define FCR		(0x4) 
#define LCR		(0x6) 
#define MCR		(0x8) 
#define LSR		(0xA) 
#define SCR		(0xE) 
#define DLL		(0x10)
#define DLH		(0x12) 
#define PWREMU_MGMT		(0x18) 

#define ETBEI ((regs->ier >> 1) & 0x1)
#define ERBI (regs->ier & 0x1)
#define ELSI ((regs->ier >> 2) & 0x1)
#define FIFOEN ((regs->iir >> 6) & 0x3)
#define IPEND ((regs->iir & 0x1)
#define THRE ((regs->lsr >> 5) & 0x1)
#endif
